name: Node CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [18, 20]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install Gatsby
      run: npm i -g gatsby

    - name: Install Dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test

    - name: Run Code Coverage
      uses: codecov/codecov-action@v2
